# require を削除し、plugins のみ使用
plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false # 不要な gem 提案を無効化
  Exclude:
    - "bin/*"
    - "config/**/*"
    - "db/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "storage/**/*"
    - "node_modules/**/*"
    - ".git/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "spec/**/*"
    - "config/routes.rb"
    - "config/environments/*"

Rails/OutputSafety:
  Enabled: false

Layout/LineLength:
  Max: 120
